/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymgtsystem.ui.home.Librarian;

import java.awt.Color;
import javax.swing.JFrame;
import librarymgtsystem.ui.addBook.addBook;
import librarymgtsystem.ui.manageBooks.manageBooks;
import librarymgtsystem.ui.manageMembers.manageMembers;

/**
 *
 * @author Dinith
 */
public class homeLibrarian extends javax.swing.JFrame {

    /**
     * Creates new form homeScreen
     */
    public homeLibrarian() {
        initComponents();
        pnlUser.setBackground(new Color(0,0,0,125));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser = new javax.swing.JPanel();
        userIco = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnReturnBook = new javax.swing.JButton();
        btnManageMembers = new javax.swing.JButton();
        btnManageBooks = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnIssueBook = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/user.png"))); // NOI18N
        pnlUser.add(userIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 50));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Welcome");
        pnlUser.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnReturnBook.setBackground(new java.awt.Color(153, 102, 0));
        btnReturnBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReturnBook.setForeground(new java.awt.Color(0, 0, 0));
        btnReturnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/return.png"))); // NOI18N
        btnReturnBook.setText("Book Return");
        btnReturnBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookActionPerformed(evt);
            }
        });
        pnlUser.add(btnReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 230, 90));

        btnManageMembers.setBackground(new java.awt.Color(153, 102, 0));
        btnManageMembers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageMembers.setForeground(new java.awt.Color(0, 0, 0));
        btnManageMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/add-user (1).png"))); // NOI18N
        btnManageMembers.setText("Manage Members");
        btnManageMembers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnManageMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMembersActionPerformed(evt);
            }
        });
        pnlUser.add(btnManageMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 230, 90));

        btnManageBooks.setBackground(new java.awt.Color(153, 102, 0));
        btnManageBooks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageBooks.setForeground(new java.awt.Color(0, 0, 0));
        btnManageBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/book (1).png"))); // NOI18N
        btnManageBooks.setText("Manage Books");
        btnManageBooks.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnManageBooks.setMaximumSize(new java.awt.Dimension(181, 66));
        btnManageBooks.setMinimumSize(new java.awt.Dimension(181, 66));
        btnManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBooksActionPerformed(evt);
            }
        });
        pnlUser.add(btnManageBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 230, 90));

        btnDashboard.setBackground(new java.awt.Color(153, 102, 0));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(0, 0, 0));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        pnlUser.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 230, 90));

        btnIssueBook.setBackground(new java.awt.Color(153, 102, 0));
        btnIssueBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIssueBook.setForeground(new java.awt.Color(0, 0, 0));
        btnIssueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/book (2).png"))); // NOI18N
        btnIssueBook.setText("Book Issue");
        btnIssueBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookActionPerformed(evt);
            }
        });
        pnlUser.add(btnIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, 90));

        getContentPane().add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 770, 690));

        btnLogout.setBackground(new java.awt.Color(0, 204, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/log-out.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 150, 50));

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/home_bg.jpg"))); // NOI18N
        getContentPane().add(bgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnBookActionPerformed

    private void btnManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBooksActionPerformed
        // TODO add your handling code here:
        JFrame manageBooks = new manageBooks();
        manageBooks.setVisible(true);
        manageBooks.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnManageBooksActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssueBookActionPerformed

    private void btnManageMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMembersActionPerformed
        // TODO add your handling code here:
        JFrame manageMembers = new manageMembers();
        manageMembers.setVisible(true);
        manageMembers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnManageMembersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeLibrarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnIssueBook;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageBooks;
    private javax.swing.JButton btnManageMembers;
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JLabel userIco;
    // End of variables declaration//GEN-END:variables
}
