/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymgtsystem.ui.home.Admin;

import java.awt.Color;
import javax.swing.JFrame;
import librarymgtsystem.ui.addBook.addBook;
import librarymgtsystem.ui.login.loginForm;
import librarymgtsystem.ui.manageBooks.manageBooks;
import librarymgtsystem.ui.manageLibrarians.manageLibrarians;
/**
 *
 * @author Omicron
 */
public class homeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form homeAdmin
     */
    public homeAdmin() {
        initComponents();
         pnlAdmin.setBackground(new Color(0,0,0,125));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        userIco = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnManageLibrarians = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/user.png"))); // NOI18N
        pnlAdmin.add(userIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 50));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Welcome");
        pnlAdmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnManageLibrarians.setBackground(new java.awt.Color(153, 102, 0));
        btnManageLibrarians.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageLibrarians.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/add-user (1).png"))); // NOI18N
        btnManageLibrarians.setText("Manage Librarians");
        btnManageLibrarians.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnManageLibrarians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLibrariansActionPerformed(evt);
            }
        });
        pnlAdmin.add(btnManageLibrarians, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 230, 90));

        btnDashboard.setBackground(new java.awt.Color(153, 102, 0));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        pnlAdmin.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 230, 90));

        getContentPane().add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 770, 560));

        btnLogout.setBackground(new java.awt.Color(0, 204, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/log-out.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 20, 150, 50));

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/home_bg.jpg"))); // NOI18N
        bgImg.setText("jLabel1");
        getContentPane().add(bgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageLibrariansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLibrariansActionPerformed
        // TODO add your handling code here:
        JFrame manageLibrarians = new manageLibrarians();
        manageLibrarians.setVisible(true);
        manageLibrarians.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnManageLibrariansActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame home = new homeAdmin();
        home.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         this.dispose();
        JFrame login = new loginForm();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageLibrarians;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JLabel userIco;
    // End of variables declaration//GEN-END:variables
}
