/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymgtsystem.ui.signup;

import librarymgtsystem.app.user.Signup;
import librarymgtsystem.ui.login.loginForm;

import javax.swing.*;

/**
 *
 * @author Dinith
 */
public class signupForm extends javax.swing.JFrame {

    /**
     * Creates new form signupForm
     */
    public signupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarLogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin1 = new javax.swing.JLabel();
        formLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        containerLogin = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        checkShowpassword = new javax.swing.JCheckBox();
        lblLastName = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        lblConfirmPassword = new javax.swing.JLabel();
        tfConfirmPassword = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarLogin.setBackground(new java.awt.Color(153, 102, 0));
        sidebarLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtLogin.setText("Librarian");
        sidebarLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/add-user.png"))); // NOI18N
        sidebarLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 130, 140));

        txtLogin1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtLogin1.setForeground(new java.awt.Color(0, 0, 0));
        txtLogin1.setText("Signup");
        sidebarLogin.add(txtLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        getContentPane().add(sidebarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        formLogin.setBackground(new java.awt.Color(255, 255, 255));
        formLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Library Management System");
        formLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/book.png"))); // NOI18N
        formLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        containerLogin.setBackground(new java.awt.Color(204, 204, 204));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(153, 102, 0));
        lblFirstName.setText("First name");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 102, 0));
        lblPassword.setText("Password");

        tfFirstName.setBackground(new java.awt.Color(255, 255, 255));
        tfFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfFirstName.setForeground(new java.awt.Color(0, 0, 0));
        tfFirstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstNameActionPerformed(evt);
            }
        });

        tfPassword.setBackground(new java.awt.Color(255, 255, 255));
        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(0, 0, 0));
        tfPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        btnSignup.setBackground(new java.awt.Color(153, 102, 0));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Signup");
        btnSignup.setBorder(null);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        checkShowpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkShowpassword.setForeground(new java.awt.Color(0, 0, 0));
        checkShowpassword.setText("Show password");
        checkShowpassword.setAlignmentY(1.0F);
        checkShowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkShowpasswordActionPerformed(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(153, 102, 0));
        lblLastName.setText("Last name");

        tfLastName.setBackground(new java.awt.Color(255, 255, 255));
        tfLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfLastName.setForeground(new java.awt.Color(0, 0, 0));
        tfLastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tfLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastNameActionPerformed(evt);
            }
        });

        lblConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(153, 102, 0));
        lblConfirmPassword.setText("Confrim password");

        tfConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        tfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        tfConfirmPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 102, 0));
        lblUsername.setText("Username");

        tfUsername.setBackground(new java.awt.Color(255, 255, 255));
        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(0, 0, 0));
        tfUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLoginLayout = new javax.swing.GroupLayout(containerLogin);
        containerLogin.setLayout(containerLoginLayout);
        containerLoginLayout.setHorizontalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLoginLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLoginLayout.createSequentialGroup()
                        .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFirstName)
                                .addComponent(lblLastName)
                                .addComponent(lblUsername))
                            .addGroup(containerLoginLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(checkShowpassword)))
                        .addGap(56, 56, 56)
                        .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(containerLoginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblConfirmPassword))
                        .addGap(21, 21, 21)
                        .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        containerLoginLayout.setVerticalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addGap(18, 18, 18)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLoginLayout.createSequentialGroup()
                        .addComponent(checkShowpassword)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLoginLayout.createSequentialGroup()
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        formLogin.add(containerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 450, 390));

        getContentPane().add(formLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 570, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstNameActionPerformed

    private void checkShowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkShowpasswordActionPerformed
        // TODO add your handling code here:
        if(checkShowpassword.isSelected()){
            tfConfirmPassword.setEchoChar((char)0);
        }
        else{
            tfConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkShowpasswordActionPerformed

    private void tfLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLastNameActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        String firstName = tfFirstName.getText();
        String lastName = tfLastName.getText();
        String username = tfUsername.getText();
        String password = new String(tfPassword.getPassword()); 
        String confirmPassword = new String(tfConfirmPassword.getPassword());
        
        if(firstName.equals("") || lastName.equals("") || username.equals("") || password.equals("") || confirmPassword.equals("")){
            JOptionPane.showMessageDialog(null, "All the field are required", "Alert", JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(!password.equals(confirmPassword)){
                JOptionPane.showMessageDialog(null, "Invalid password!", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            else{
                
                Signup signup = new Signup(firstName, lastName, username, password);
                if (signup.isValidUser()){
                    signup.allowRegistration();
                    this.dispose();
                    JFrame login = new loginForm();
                    login.setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "User already exists!", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JCheckBox checkShowpassword;
    private javax.swing.JPanel containerLogin;
    private javax.swing.JPanel formLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel sidebarLogin;
    private javax.swing.JPasswordField tfConfirmPassword;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtLogin1;
    // End of variables declaration//GEN-END:variables
}
