/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymgtsystem.ui.manageBooks;

import librarymgtsystem.ui.manageMembers.*;
import java.sql.*;
import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import librarymgtsystem.app.book.Book;
import librarymgtsystem.database.DBConnection;
import librarymgtsystem.ui.addBook.addBook;
import librarymgtsystem.ui.addMember.AddMember;
import librarymgtsystem.ui.home.Librarian.homeLibrarian;
import librarymgtsystem.ui.login.loginForm;
import librarymgtsystem.ui.updateBook.UpdateBook;
import librarymgtsystem.ui.updateMember.updateMember;
/**
 *
 * @author Dinith
 */
public class manageBooks extends javax.swing.JFrame {
    private Connection conn;

    /**
     * Creates new form manageMembers
     */
    public manageBooks() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        btnDeleteBook = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnUpdateBook = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        sideBar = new javax.swing.JPanel();
        btnAddBook1 = new javax.swing.JButton();
        btnIssueBook1 = new javax.swing.JButton();
        btnReturnBook1 = new javax.swing.JButton();
        btnDashboard1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUser.setBackground(new java.awt.Color(102, 102, 102));
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book Title", "ISBN", "Author", "Publisher", "Category", "Availability"
            }
        ));
        tblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBooks);

        pnlUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 30, 710, 530));

        btnDeleteBook.setBackground(new java.awt.Color(153, 102, 0));
        btnDeleteBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/delete.png"))); // NOI18N
        btnDeleteBook.setText("Delete Book");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });
        pnlUser.add(btnDeleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 190, 50));

        btnAddBook.setBackground(new java.awt.Color(153, 102, 0));
        btnAddBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/plus.png"))); // NOI18N
        btnAddBook.setText("Add Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        pnlUser.add(btnAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 50));

        btnUpdateBook.setBackground(new java.awt.Color(153, 102, 0));
        btnUpdateBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/refresh.png"))); // NOI18N
        btnUpdateBook.setText("Update Book");
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });
        pnlUser.add(btnUpdateBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 50));

        getContentPane().add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 980, 680));

        btnLogout.setBackground(new java.awt.Color(0, 204, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/log-out.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 150, 50));

        sideBar.setBackground(new java.awt.Color(153, 153, 153));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddBook1.setBackground(new java.awt.Color(153, 102, 0));
        btnAddBook1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddBook1.setForeground(new java.awt.Color(0, 0, 0));
        btnAddBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/book (1).png"))); // NOI18N
        btnAddBook1.setText("Manage Books");
        btnAddBook1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddBook1.setMaximumSize(new java.awt.Dimension(181, 66));
        btnAddBook1.setMinimumSize(new java.awt.Dimension(181, 66));
        btnAddBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBook1ActionPerformed(evt);
            }
        });
        sideBar.add(btnAddBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 90));

        btnIssueBook1.setBackground(new java.awt.Color(153, 102, 0));
        btnIssueBook1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIssueBook1.setForeground(new java.awt.Color(0, 0, 0));
        btnIssueBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/book (2).png"))); // NOI18N
        btnIssueBook1.setText("Book Issue");
        btnIssueBook1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIssueBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBook1ActionPerformed(evt);
            }
        });
        sideBar.add(btnIssueBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 90));

        btnReturnBook1.setBackground(new java.awt.Color(153, 102, 0));
        btnReturnBook1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReturnBook1.setForeground(new java.awt.Color(0, 0, 0));
        btnReturnBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/return.png"))); // NOI18N
        btnReturnBook1.setText("Book Return");
        btnReturnBook1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturnBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBook1ActionPerformed(evt);
            }
        });
        sideBar.add(btnReturnBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 230, 90));

        btnDashboard1.setBackground(new java.awt.Color(153, 102, 0));
        btnDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDashboard1.setForeground(new java.awt.Color(0, 0, 0));
        btnDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/dashboard.png"))); // NOI18N
        btnDashboard1.setText("Dashboard");
        btnDashboard1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard1ActionPerformed(evt);
            }
        });
        sideBar.add(btnDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 230, 90));

        btnBack.setOpaque(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/undo.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        sideBar.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 80));

        getContentPane().add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 780));

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/home_bg.jpg"))); // NOI18N
        getContentPane().add(bgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void loadAllDataIntoTable(List<Book> list){
        DefaultTableModel tbl =(DefaultTableModel) tblBooks.getModel();
        tbl.setRowCount(0);

        for(Book book : list){
            int av = book.getAvailability();
            String availability;
        if(av==1){
            availability ="Available";
        }
        else{
            availability ="Unavailable";
        }
            Vector v = new Vector();
            v.add(book.getId());
            v.add(book.getTitle());
            v.add(book.getIsbn());
            v.add(book.getAuthor());
            v.add(book.getPublisher());
            v.add(book.getCategory());
            v.add(availability);
            v.add(book.getCreated_at());
            
            tbl.addRow(v);
            }
        
    }
    public static void loadTable(){
        Book book = new Book();
        List list = book.viewAllBooks();
        loadAllDataIntoTable(list);
    }
    
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame login = new loginForm();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBook1ActionPerformed

    private void btnIssueBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssueBook1ActionPerformed

    private void btnReturnBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnBook1ActionPerformed

    private void btnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard1ActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        // TODO add your handling code here:
         int selectedRow = this.tblBooks.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select any record to delete");
        }
        else{
            int id = (int)tblBooks.getValueAt(selectedRow, 0);
            
        }
        int id = Integer.parseInt(this.tblBooks.getValueAt(selectedRow, 0).toString());
        
        Book book = new Book();
        book.deleteBook(id);
        loadTable();
        
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        JFrame addBook = new addBook();
        addBook.setVisible(true);
        addBook.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed
        // TODO add your handling code here:
        
        int  selectedRow = this.tblBooks.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select any record to update");
        }
        else{
            int id = (int)tblBooks.getValueAt(selectedRow, 0);
            
        }
        int id = Integer.parseInt(this.tblBooks.getValueAt(selectedRow, 0).toString());
        String title = this.tblBooks.getValueAt(selectedRow, 1).toString();
        String isbn = this.tblBooks.getValueAt(selectedRow, 2).toString();
        String author = this.tblBooks.getValueAt(selectedRow, 3).toString();
        String publisher = this.tblBooks.getValueAt(selectedRow, 4).toString();
        String category = this.tblBooks.getValueAt(selectedRow, 5).toString();
        String availability = this.tblBooks.getValueAt(selectedRow, 6).toString();
        
        JFrame updateBook = new UpdateBook();
        
        JLabel bookId = UpdateBook.lblBookId;
        bookId.setVisible(false);
        
        JTextField bookTitle = UpdateBook.tfBookTitle;
        bookTitle.setText(title);
        
        JTextField bookisbn = UpdateBook.tfBookTitle;
        bookTitle.setText(title);
        
        JTextField bookIsbn = UpdateBook.tfISBN;
        bookIsbn.setText(isbn);
        
        JTextField bookAuthor= UpdateBook.tfAuthor;
        bookAuthor.setText(author);
        
        JTextField bookPublisher = UpdateBook.tfPublisher;
        bookPublisher.setText(publisher);
        
        JComboBox<String> bookCategory = UpdateBook.cmbCategory;
        bookCategory.setSelectedItem(category);
        
        JComboBox<String> bookAvailability = UpdateBook.cmbAvailability;
        bookAvailability.setSelectedItem(availability);
        
        updateBook.setVisible(true);
        updateBook.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        this.dispose();
        JFrame home = new homeLibrarian();
        home.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBooksMouseClicked
        // TODO add your handling code here:
         int row =tblBooks.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select any record.");
        }
        else{
            int id = (int)tblBooks.getValueAt(row, 0);
            
        }
    }//GEN-LAST:event_tblBooksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddBook1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDashboard1;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnIssueBook1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReturnBook1;
    private javax.swing.JButton btnUpdateBook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel sideBar;
    public static javax.swing.JTable tblBooks;
    // End of variables declaration//GEN-END:variables
}
