/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymgtsystem.ui.login;

import com.mysql.cj.callback.UsernameCallback;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import librarymgtsystem.ui.home.Librarian.homeLibrarian;
import librarymgtsystem.app.user.Login;
import librarymgtsystem.ui.home.Admin.homeAdmin;

//import librarymgtsystem.ui.manageLibrarians.manageLibrarians;
//import librarymgtsystem.ui.signup.signupForm;

import librarymgtsystem.ui.signup.signupForm;


/**
 *
 * @author Dinith
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarLogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        containerLogin = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        checkShowpassword = new javax.swing.JCheckBox();
        btnNavSignup = new javax.swing.JButton();
        comboUserType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarLogin.setBackground(new java.awt.Color(153, 102, 0));
        sidebarLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtLogin.setText("Login");
        sidebarLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/password.png"))); // NOI18N
        sidebarLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 140));

        getContentPane().add(sidebarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        formLogin.setBackground(new java.awt.Color(255, 255, 255));
        formLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Library Management System");
        formLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/book.png"))); // NOI18N
        formLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        containerLogin.setBackground(new java.awt.Color(204, 204, 204));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 102, 0));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 102, 0));
        lblPassword.setText("Password");

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        btnLogin.setBackground(new java.awt.Color(153, 102, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        checkShowpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkShowpassword.setText("Show password");
        checkShowpassword.setAlignmentY(1.0F);
        checkShowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkShowpasswordActionPerformed(evt);
            }
        });

        btnNavSignup.setBackground(new java.awt.Color(204, 204, 204));
        btnNavSignup.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnNavSignup.setForeground(new java.awt.Color(153, 102, 0));
        btnNavSignup.setText("Signup");
        btnNavSignup.setBorder(null);
        btnNavSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLoginLayout = new javax.swing.GroupLayout(containerLogin);
        containerLogin.setLayout(containerLoginLayout);
        containerLoginLayout.setHorizontalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLoginLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkShowpassword)
                            .addGroup(containerLoginLayout.createSequentialGroup()
                                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPassword))
                                .addGap(72, 72, 72)
                                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(tfPassword))))))
                    .addGroup(containerLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnNavSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        containerLoginLayout.setVerticalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(checkShowpassword)
                .addGap(27, 27, 27)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnNavSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        formLogin.add(containerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 450, 370));

        comboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Librarian" }));
        comboUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUserTypeActionPerformed(evt);
            }
        });
        formLogin.add(comboUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 160, 30));

        getContentPane().add(formLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 570, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed
    
    //show password option
    private void checkShowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkShowpasswordActionPerformed
        // TODO add your handling code here:
        if(checkShowpassword.isSelected()){
            tfPassword.setEchoChar((char)0);
        }
        else{
            tfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkShowpasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = tfUsername.getText();
        String password = new String(tfPassword.getPassword());
        String userType = comboUserType.getSelectedItem().toString();
        
        if(username.equals("") || password.equals("")){
            if(username.equals("") && password.equals("")){
                JOptionPane.showMessageDialog(null, "Username and password fields are empty!", "Alert",JOptionPane.WARNING_MESSAGE);
            }
            else if(username.equals("")){
                JOptionPane.showMessageDialog(null, "Username is empty!", "Alert",JOptionPane.WARNING_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Password is empty!", "Alert",JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            Login login = new Login(username, password, userType);
            if(login.getValidStatus()){
                if(userType.equals("Admin")){
                    JFrame home = new homeAdmin();
                    home.setVisible(true);
                }
                else{
                    int loginID = login.getLibrarianID();
                    JFrame home = new homeLibrarian();
                    home.setVisible(true);
                }
                this.dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid username or password", "Alert",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void comboUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUserTypeActionPerformed

    private void btnNavSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavSignupActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame signup = new signupForm();
        signup.setVisible(true);
    }//GEN-LAST:event_btnNavSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNavSignup;
    private javax.swing.JCheckBox checkShowpassword;
    private javax.swing.JComboBox<String> comboUserType;
    private javax.swing.JPanel containerLogin;
    private javax.swing.JPanel formLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel sidebarLogin;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel txtLogin;
    // End of variables declaration//GEN-END:variables
}
