/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymgtsystem.ui.manageLibrarians;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import librarymgtsystem.database.DBConnection;
import librarymgtsystem.ui.addLibrarian.addLibrarian;
import librarymgtsystem.ui.home.Admin.homeAdmin;
import librarymgtsystem.ui.login.loginForm;
import librarymgtsystem.ui.updateLibrarian.UpdateLibrarian;

/**
 *
 * @author Dinith
 */
public class manageLibrarians extends javax.swing.JFrame {
     private Connection conn;
     
    /**
     * Creates new form homeAdmin
     */
    public manageLibrarians() {
        initComponents();
        //pnlAdmin.setBackground(new Color(0,0,0,150));
        this.retrieveLibrarians();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void retrieveLibrarians(){
        try {
            this.conn = DBConnection.connect();
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM tbl_librarian";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                int index = 0;
                
                int id = rs.getInt("ID");
                String firstName = rs.getString("First name");
                String lastName = rs.getString("Last name");
                String username = rs.getString("username");
                String password = rs.getString("password");
                
                Object[] row = {id, firstName, lastName, username, password};
                
                DefaultTableModel model = (DefaultTableModel) this.tblLibrarian.getModel();
                
                model.addRow(row);    
            }
            
        } 
        catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        userIco = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLibrarian = new javax.swing.JTable();
        btnUpdateLibrarian = new javax.swing.JButton();
        btnAddLibrarian = new javax.swing.JButton();
        btnDeleteLibrarian = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAdmin.setBackground(new java.awt.Color(102, 102, 102));
        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/user.png"))); // NOI18N
        pnlAdmin.add(userIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 50));

        tblLibrarian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblLibrarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0001", "Dinith", "Kumudika", "dinith"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Username"
            }
        ));
        jScrollPane2.setViewportView(tblLibrarian);

        pnlAdmin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 800, 610));

        btnUpdateLibrarian.setBackground(new java.awt.Color(0, 102, 255));
        btnUpdateLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateLibrarian.setText("Update");
        btnUpdateLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLibrarianActionPerformed(evt);
            }
        });
        pnlAdmin.add(btnUpdateLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, 40));

        btnAddLibrarian.setBackground(new java.awt.Color(51, 204, 0));
        btnAddLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddLibrarian.setText("Add");
        btnAddLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibrarianActionPerformed(evt);
            }
        });
        pnlAdmin.add(btnAddLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 120, 40));

        btnDeleteLibrarian.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteLibrarian.setText("Delete");
        pnlAdmin.add(btnDeleteLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 120, 40));

        getContentPane().add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1180, 670));

        btnLogout.setBackground(new java.awt.Color(0, 204, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/log-out.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 150, 50));

        btnDashboard.setBackground(new java.awt.Color(153, 102, 0));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 250, 70));

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymgtsystem/assets/home_bg.jpg"))); // NOI18N
        bgImg.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        getContentPane().add(bgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame login = new loginForm();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibrarianActionPerformed
        // TODO add your handling code here:
        JFrame addLibrarian = new addLibrarian();
        addLibrarian.setVisible(true);
        addLibrarian.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnAddLibrarianActionPerformed

    private void btnUpdateLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLibrarianActionPerformed
        // TODO add your handling code here:
        int  selectedRow = this.tblLibrarian.getSelectedRow();
        int id = Integer.parseInt(this.tblLibrarian.getValueAt(selectedRow, 0).toString());
        String firstName = this.tblLibrarian.getValueAt(selectedRow, 1).toString();
        String lastName = this.tblLibrarian.getValueAt(selectedRow, 2).toString();
        String username = this.tblLibrarian.getValueAt(selectedRow, 3).toString();
        String password = this.tblLibrarian.getValueAt(selectedRow, 4).toString();
        //String password = this.tblLibrarian.getValueAt(selectedRow, 4).toString();
        
        JFrame UpdateLibrarianFrame = new UpdateLibrarian();
        
        //set name value got from table row to name textfield in UpdateLibrarian frame
        JTextField firstNameField = UpdateLibrarian.tfFirstName;
        firstNameField.setText(firstName);
        
        //set age Value got from table row to age textfield in UpdateLibrarian frame
        JTextField lastNameField = UpdateLibrarian.tfLastName;
        lastNameField.setText(lastName);
        
        //set address Value got from table row to age textfield in UpdateLibrarian frame
        JTextField UsernameField = UpdateLibrarian.tfUsername;
        UsernameField.setText(username);
        
        //set phone no Value got from table row to age textfield in UpdateLibrarian frame
        JTextField passwordField = UpdateLibrarian.tfPassword;
        passwordField.setText(password);
        
        UpdateLibrarianFrame.setVisible(true);
        UpdateLibrarianFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnUpdateLibrarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageLibrarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageLibrarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageLibrarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageLibrarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageLibrarians().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JButton btnAddLibrarian;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDeleteLibrarian;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateLibrarian;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JTable tblLibrarian;
    private javax.swing.JLabel userIco;
    // End of variables declaration//GEN-END:variables
}
